In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir()

['Data_cleaning_Olympics.ipynb',
 'domain_name.py',
 'Olympics-Dataset',
 'PandasPractice']

In [4]:
df = pd.read_csv('Olympics-Dataset/athletes/bios.csv')

In [5]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
bios = df.copy()

In [38]:
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

In [36]:
def get_names(x):
    # print('here')
    return  x.split('•')[0] +" "+ x.split('•')[1]
bios['Name'] =bios['Used name'].apply(lambda x:get_names(x))

## Another way
# bios['Name'] = bios['Used name].replace('•'," ")

In [134]:
import pandas as pd 
def get_measurements(measure): 
    if type(measure) == float and pd.isna(measure): 
        return pd.NA, pd.NA 
    # Return NaN values for height and weight if not entered 
    elif isinstance(measure, str): 
        parts = measure.split('/') 
        if len(parts) >= 2: 
            return parts[0].strip(), parts[1].strip() 
        # Return height and weight 
        else: return pd.NA, pd.NA 
        # Return NaN values if format is invalid 
    else: return pd.NA, pd.NA 
        # Return NaN values for invalid input 
        # Apply the get_measurements function to the 'Measurements' column 
bios[['height', 'weight']] = bios['Measurements'].apply(lambda x: pd.Series(get_measurements(x))) # Drop the 'Measurements' column if needed bios.drop(columns=['Measurements'], inplace=True)

In [135]:
## Another way of doing it
bios[['height_cm','weight_kg']] =bios['Measurements'].str.split('/',expand=True)

In [137]:
# bios = bios.drop(columns=['height','weight''])
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,Name,height_cm,weight_kg,height,weight
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,<NA>,<NA>
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,<NA>,<NA>

In [142]:
bios['weight_kg'].fillna(bios['height_cm'],inplace=True)
# bios['height_cm'].fillna(bios['weight_kg'],inplace=True)

In [147]:

def return_height(x):
    # print('here')
    if type(x) == float and pd.isna(x):  
        return x
    elif 'cm' in x:
        return  x.split(' cm')[0]
    
bios['height'] = bios['height_cm'].apply(lambda x :return_height(x))
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,Name,height_cm,weight_kg,height,weight
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg,183,76
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg,183,76
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg,168,64
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,NaN,NaN

In [149]:
def return_weight(x):
    # print('here')
    if type(x) == float and pd.isna(x) or x==None:  
        return x
    elif 'kg' in x:

        return  x.split(' kg')[0]
bios['weight'] = bios['weight_kg'].apply(lambda x :return_weight(x))

In [151]:
bios[(~bios['weight_kg'].isna())&(bios['weight_kg'].str.contains('cm'))]
bios[(~bios['height_cm'].isna())&(bios['height_cm'].str.contains('kg'))]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,Name,height_cm,weight_kg,height,weight
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Patricia Offel,120 kg,120 kg,None,120
289,Competed in Olympic Games,Male,Ángel•Bello,Ángel•Bello,"9 January 1951 in Vigo, Pontevedra (ESP)",13 June 2013,Argentina,290,65 kg,"Tiro Federal de Lomas de Zamora, Lomas de Zamo...",...,NaN,NaN,NaN,NaN,NaN,Ángel Bello,65 kg,65 kg,None,65
290,Competed in Olympic Games,Male,Claudio A.•Pafundi,Claudio•Pafundi,31 January 1962,NaN,Argentina,291,76 kg,"Tiro Federal General José de San Martín, San M...",...,NaN,NaN,NaN,NaN,NaN,Claudio Pafundi,76 kg,76 kg,None,76
1128,Competed in Olympic Games,Male,Jeffrey O.•Alleyne,Jeffrey•Alleyne,"25 June 1938 in Bridgetown, Saint Michael (BAR)",NaN,Canada,1135,71 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Jeffrey Alleyne,71 kg,71 kg,None,71
1132,Competed in Olympic Games,Male,"Edward ""Ed""•Beattie",Ed•Beattie,"4 February 1934 in Kilsyth, Scotland (GBR)",NaN,Canada,1139,60 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Ed Beattie,60 kg,60 kg,None,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143193,Competed in Olympic Games,Male,Rejepbaý•Rejepow,Rejepbaý•Rejepow,23 February 1992,NaN,Turkmenistan,146829,81 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Rejepbaý Rejepow,81 kg,81 kg,None,81
143225,Competed in Olympic Games,Male,Chen•Po-Jen,Chen•Po-Jen,11 May 1998,NaN,Chinese Taipei,146865,96 kg,NaN,...,NaN,NaN,NaN,陳•柏任,Oriental,Chen Po-Jen,96 kg,96 kg,None,96
143542,Competed in Olympic Games,Female,Nefeli•Papadakis,Nefeli•Papadakis,"2 October 1998 in Chicago, Illinois (USA)",NaN,United States,147195,78 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Nefeli Papadakis,78 kg,78 kg,None,78
143852,Competed in Olympic Games,Male,Kyle Douglas•Dake,Kyle•Dake,"25 February 1991 in Ithaca, New York (USA)",NaN,United States,147508,79 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Kyle Dake,79 kg,79 kg,None,79
144122,Competed in Olympic Games,Female,Scarleth•Ucelo Marroquín,Scarleth•Ucelo,7 April 2000,NaN,Guatemala,147795,114 kg,NaN,...,NaN,NaN,NaN,NaN,NaN,Scarleth Ucelo,114 kg,114 kg,None,114

In [168]:
import re
import datetime as dt
bios['Born_Date'] = bios['Born'].str.extract(r'(\d+ \w+ \d{4})| \d{4}')
bios.Born_Date.value_counts()

1 January 1975      17
10 May 1971         17
1 January 1970      16
13 October 1972     16
19 December 1985    15
                    ..
1 October 1960       1
11 April 1917        1
5 May 1917           1
1 May 1891           1
31 August 1998       1
Name: Born_Date, Length: 41256, dtype: int64

In [172]:
bios['Death_date'] =  bios['Died'].str.extract(r'(\d+ \w+ \d{4})| \d{4}')
pd.to_datetime(bios['Death_date']).dt.year.value_counts()

2021.0    730
2020.0    720
2022.0    674
2018.0    627
2017.0    615
         ...
1901.0      5
1906.0      5
1900.0      3
1903.0      2
1902.0      2
Name: Death_date, Length: 124, dtype: int64

In [183]:
pd.set_option('max_colwidth', None) 
bios.head(10)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Nationality,Original name,Name order,Name,height_cm,weight_kg,height,weight,Born_Date,Death_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•Blanchy",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-Atlantiques (FRA)",France,1,NaN,NaN,...,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,NaN,NaN,12 December 1886,2 October 1960
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg,183,76,1 April 1969,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiques (FRA)","17 July 1994 in Arbonne, Pyrénées-Atlantiques (FRA)",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg,183,76,13 August 1898,17 July 1994
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg,168,64,11 May 1895,20 March 1978
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,Albert Canet,NaN,NaN,NaN,NaN,17 April 1878,25 July 1930
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",...,NaN,NaN,NaN,Nicolas Chatelain,181 cm,70 kg,181,70,13 January 1970,NaN
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal Villette Charleroi, Charleroi (BEL) / Espérance de Reuilly Tennis de Table, Paris (FRA) / Levallois SCTT, Levallois-Perret (FRA)",...,NaN,NaN,NaN,Patrick Chila,180 cm,73 kg,180,73,27 November 1969,NaN
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yvelines (FRA)",France,8,NaN,NaN,...,NaN,NaN,NaN,Henri Cochet,NaN,NaN,NaN,NaN,14 December 1901,2 April 1987
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,...,NaN,NaN,NaN,Marcel Cousin,NaN,NaN,NaN,NaN,4 August 1896,1 August 1986
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,...,NaN,NaN,NaN,Guy de la Chapelle,NaN,NaN,NaN,NaN,16 July 1868,27 August 1923

In [185]:
# df[['Born_City','Born_Region','Born_country']] =
bios[['born_city','born_region','born_country']]=bios['Born'].str.extract(r'in ([\w\s-]+),\s+([\w\s-]+)\s+\(([\w\s-]+)\)')
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name,height_cm,weight_kg,height,weight,Born_Date,Death_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•Blanchy",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-Atlantiques (FRA)",France,1,NaN,NaN,...,Jean-François Blanchy,NaN,NaN,NaN,NaN,12 December 1886,2 October 1960,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,Arnaud Boetsch,183 cm,76 kg,183,76,1 April 1969,NaN,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiques (FRA)","17 July 1994 in Arbonne, Pyrénées-Atlantiques (FRA)",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,Jean Borotra,183 cm,76 kg,183,76,13 August 1898,17 July 1994,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,Jacques Brugnon,168 cm,64 kg,168,64,11 May 1895,20 March 1978,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,Albert Canet,NaN,NaN,NaN,NaN,17 April 1878,25 July 1930,Wandsworth,England,GBR

In [188]:
## columns to keep
bios_cleaned = bios[['Roles','Sex','NOC','athlete_id','height','weight','Born_Date','Death_date','born_city','born_region','born_country']]

,Roles,Sex,NOC,athlete_id,height,weight,Born_Date,Death_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,France,1,NaN,NaN,12 December 1886,2 October 1960,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,France,2,183,76,1 April 1969,NaN,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,France,3,183,76,13 August 1898,17 July 1994,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,France,4,168,64,11 May 1895,20 March 1978,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,France,5,NaN,NaN,17 April 1878,25 July 1930,Wandsworth,England,GBR
...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,ROC,149222,167,61,30 January 2002,NaN,Serov,Sverdlovsk,RUS
145496,Competed in Olympic Games,Female,ROC,149223,168,65,20 September 1999,NaN,NaN,NaN,NaN
145497,Competed in Olympic Games,Female,ROC,149224,163,55,8 May 1998,NaN,Kotlas,Arkhangelsk,RUS
145498,Competed in Olympic Games,Male,France,149225,166,None,19 May 1899,18 March 1986,Niort,Deux-Sèvres,FRA
145499,Non-starter • Administrator,Male,Australia,149814,NaN,NaN,15 July 1913,20 October 2003,Dulwich Hill,New South Wales,AUS